export interface IUser {
  id: string;
  name: string;
  firstName?: string;
  lastName?: string;
  email: string;
  personalEmail?: string;
  passwordHash: string;
  avatar?: string;
  role: 'ADMIN' | 'HOD' | 'REGULAR_TEACHER' | 'VISITING_TEACHER';
  departmentId: string;
  departmentName: string;
  designation: string;
  phone: string;
  altPhone?: string;
  officeExtension?: string;
  emergencyContact?: string;
  gender?: string;
  dob?: string;
  cnic?: string;
  maritalStatus?: string;
  bloodGroup?: string;
  nationality?: string;
  country?: string;
  state?: string;
  city?: string;
  postalCode?: string;
  officeAddress?: string;
  residentialAddress?: string;
  employeeId?: string;
  joiningDate?: string;
  employmentType?: string;
  highestQualification?: string;
  specialization?: string;
  academicSession?: string;
  username?: string;
  campus?: string;
  status: 'Active' | 'Inactive' | 'Locked' | 'Suspended';
  loginAttempts?: number;
  loginCount?: number;
  deleted?: boolean;
  lockUntil?: Date;
  contractStartDate?: string;
  contractEndDate?: string;
  supervisorName?: string;
  enrollmentStatus?: 'New' | 'ProfileIncomplete' | 'FormSubmitted' | 'PendingHODApproval' | 'Approved' | 'Rejected' | 'NeedsUpdate';
  rejectionReason?: string;
  approvedAt?: string;
  approvedBy?: string;
  totalCredits?: number;
  selectedCourseIds?: string[];
  createdAt: string;
  lastLogin: string;
  refreshToken?: string;
}

export default IUser;
